TRUNCATE openmrs_backup.form_field;
TRUNCATE openmrs_backup.htmlformentry_html_form;
delete from openmrs_backup.form where form_id not in (select distinct form_id from openmrs_backup.encounter);
delete from openmrs_backup.encounter_type where encounter_type_id not in (select distinct encounter_type from openmrs_backup.encounter);
-- ART SUMMARY
update openmrs_backup.encounter_type set encounter_type_id = 50 where encounter_type_id = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('summary',name) > 0);
update openmrs_backup.form set form_id = 50 where form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('summary',name) > 0);
update openmrs_backup.encounter set encounter_type = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('summary',name) > 0),form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('summary',name) > 0) where encounter_type IN (select encounter_type_id from openmrs_backup.encounter_type where locate('summary',name) > 0 and locate('page',name) > 0);
update openmrs_backup.encounter_type set encounter_type_id = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('summary',name) > 0) where locate('summary',name) > 0 and locate('page',name) > 0;
update openmrs_backup.form set form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('summary',name) > 0),encounter_type = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('summary',name) > 0) where locate('art',name) > 0 and locate('card',name) > 0 and locate('summary',name) > 0 and locate('new',name) = 0;

-- ART Encounter Page
update openmrs_backup.encounter_type set encounter_type_id = 60 where encounter_type_id = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0 and locate('education',name) = 0);
update openmrs_backup.form set form_id = 60 where form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0);
update openmrs_backup.encounter set encounter_type = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0 and locate('education',name) = 0),form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0) where encounter_type IN (select encounter_type_id from openmrs_backup.encounter_type where locate('encounter',name) > 0 and locate('page',name) > 0);
update openmrs_backup.encounter_type set encounter_type_id = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0 and locate('education',name) = 0) where locate('encounter',name) > 0 and locate('page',name) > 0;
update openmrs_backup.form set form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0),encounter_type = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0 and locate('education',name) = 0) where locate('art',name) > 0 and locate('card',name) > 0 and locate('encounter',name) > 0 and locate('new',form.name) = 0;

-- ART Health Education
update openmrs_backup.encounter_type set encounter_type_id = 70 where encounter_type_id = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('education',name) > 0);
update openmrs_backup.form set form_id = 70 where form_id = (SELECT form_id FROM openmrs.form WHERE locate('art', name) > 0 AND locate('card', name) > 0 AND locate('education', name) > 0);
update openmrs_backup.encounter set encounter_type = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('education',name) > 0),form_id = (select form_id from openmrs.form where locate('art',name) > 0 and locate('card',name) > 0 and locate('education',name) > 0) where encounter_type IN (select encounter_type_id from openmrs_backup.encounter_type where locate('health',name) > 0 and locate('education',name) > 0);
update openmrs_backup.encounter_type set encounter_type_id = (select encounter_type_id from openmrs.encounter_type where locate('art',name) > 0 and locate('card',name) > 0 and locate('education',name) > 0) where locate('health',name) > 0 and locate('education',name) > 0;
UPDATE openmrs_backup.form SET form_id = (SELECT form_id FROM openmrs.form WHERE locate('art', name) > 0 AND locate('card', name) > 0 AND locate('education', name) > 0), encounter_type = (SELECT encounter_type_id FROM openmrs.encounter_type WHERE locate('art', name) > 0 AND locate('card', name) > 0 AND locate('education', name) > 0) WHERE locate('art', name) > 0 AND locate('card', name) > 0 AND locate('education', name) > 0 AND locate('new', name) = 0;
