package org.openmrs.module.aijar;

/**
 * Uganda customization specific constants
 * Created by ssmusoke on 06/01/2016.
 */
public class AijarConstants {
    /**
     * Module ID
     */
    public static final String MODULE_ID = "aijar";

    /**
     * Global property names
     */
    public static final String GP_HEALTH_CENTER_NAME = MODULE_ID + ".healthCenterName";
    public static final String GP_HEALTH_CENTER_NAME_VALUE = "Health Center Name";
    public static final String GP_HEALTH_CENTER_NAME_DEFAULT_ALERT_MESSAGE="The Health Center Name is not set please go to admin then Settings then Aijar and set it";

    public static final String GP_DHIS2= "ugandaemr.dhis2.organizationuuid";
    public static final String GP_DHIS2_VALUE = "eg d06ace3e-9c46-11e7-abc4-cec278b6b50a";
    public static final String GP_NHPI = MODULE_ID + ".nhpi";
    public static final String GP_NHPI_VALUE = "HFT2ZBPE8";
    public static final String GP_NHPI_DESCRIPTION = "Allows one to set the National Health Provider Identifier";
    public static final String GP_NHPI_DEFAULT_ALERT_MESSAGE="The National Health Provider Identifier is not set please go to admin then Settings then Aijar and set it";
    public static final String GP_DHIS2_DEFAULT_ALERT_MESSAGE="The organization code in DHIS2 is not set please go to admin then Settings then Ugandaemr and set it";

    public static final String GP_DSDM_PROGRAM_UUID_NAME="ugandaemr.dsdm.programsuuid";

    public static final String GP_DSDM_CONCEPT_ID="ugandaemr.dsdm.conceptId";


    /**x
     * Concepts
     */
    public static final String UNIT_TB_NUMBER = "304df0d0-afe4-4a61-a917-d684b100a65a";
    
    public static final String HSD_TB_NUMBER = "d1cda288-4853-4450-afbc-76bd4e65ea70";
    
    public static final String DISTRICT_TB_NUMBER = "67e9ec2f-4c72-408b-8122-3706909d77ec";

    public static final String UIC_GENERATOR_QUERY =  "insert into patient_identifier (patient_id,identifier_type,date_created,preferred,location_id,creator ,changed_by,voided_by,identifier,uuid) \n"
            + "select patient_id,(select patient_identifier_type_id from patient_identifier_type where uuid='877169c4-92c6-4cc9-bf45-1ab95faea242' )as identifier,NOW() AS date_created,0 as preffered,NULL,1 AS creator,null as changed_by,null as voided_by, concat(left(country,1),'-',mid(birthdate,6,2), mid(birthdate,3,2),'-', if (gender='M', 1, 2) , '-',\n"
            + "     (CASE\n"
            + "         WHEN mid(given_name,1,1) = 'A' THEN '01'\n"
            + "         WHEN mid(given_name,1,1) = 'B' THEN '02'\n"
            + "         WHEN mid(given_name,1,1) = 'C' THEN '03'\n"
            + "         WHEN mid(given_name,1,1) = 'D' THEN '04'\n"
            + "         WHEN mid(given_name,1,1) = 'E' THEN '05'\n"
            + "         WHEN mid(given_name,1,1) = 'F' THEN '06'\n"
            + "         WHEN mid(given_name,1,1) = 'G' THEN '07'\n"
            + "         WHEN mid(given_name,1,1) = 'H' THEN '08'\n"
            + "         WHEN mid(given_name,1,1) = 'I' THEN '09'\n"
            + "         WHEN mid(given_name,1,1) = 'J' THEN '10'\n"
            + "         WHEN mid(given_name,1,1) = 'K' THEN '11'\n"
            + "         WHEN mid(given_name,1,1) = 'L' THEN '12'\n"
            + "         WHEN mid(given_name,1,1) = 'M' THEN '13'\n"
            + "         WHEN mid(given_name,1,1) = 'N' THEN '14'\n"
            + "         WHEN mid(given_name,1,1) = 'O' THEN '15'\n"
            + "         WHEN mid(given_name,1,1) = 'P' THEN '16'\n"
            + "         WHEN mid(given_name,1,1) = 'Q' THEN '17'\n"
            + "         WHEN mid(given_name,1,1) = 'R' THEN '18'\n"
            + "         WHEN mid(given_name,1,1) = 'S' THEN '19'\n"
            + "         WHEN mid(given_name,1,1) = 'T' THEN '20'\n"
            + "         WHEN mid(given_name,1,1) = 'U' THEN '21'\n"
            + "         WHEN mid(given_name,1,1) = 'V' THEN '22'\n"
            + "         WHEN mid(given_name,1,1) = 'W' THEN '23'\n"
            + "         WHEN mid(given_name,1,1) = 'X' THEN '24'\n"
            + "         WHEN mid(given_name,1,1) = 'Y' THEN '25'\n"
            + "         WHEN mid(given_name,1,1) = 'Z' THEN '26'\n"
            + "          ELSE 'X' END),\n"
            + "    (CASE\n"
            + "         WHEN mid(given_name,2,1) = 'A' THEN '01'\n"
            + "         WHEN mid(given_name,2,1) = 'B' THEN '02'\n"
            + "         WHEN mid(given_name,2,1) = 'C' THEN '03'\n"
            + "         WHEN mid(given_name,2,1) = 'D' THEN '04'\n"
            + "         WHEN mid(given_name,2,1) = 'E' THEN '05'\n"
            + "         WHEN mid(given_name,2,1) = 'F' THEN '06'\n"
            + "         WHEN mid(given_name,2,1) = 'G' THEN '07'\n"
            + "         WHEN mid(given_name,2,1) = 'H' THEN '08'\n"
            + "         WHEN mid(given_name,2,1) = 'I' THEN '09'\n"
            + "         WHEN mid(given_name,2,1) = 'J' THEN '10'\n"
            + "         WHEN mid(given_name,2,1) = 'K' THEN '11'\n"
            + "         WHEN mid(given_name,2,1) = 'L' THEN '12'\n"
            + "         WHEN mid(given_name,2,1) = 'M' THEN '13'\n"
            + "         WHEN mid(given_name,2,1) = 'N' THEN '14'\n"
            + "         WHEN mid(given_name,2,1) = 'O' THEN '15'\n"
            + "         WHEN mid(given_name,2,1) = 'P' THEN '16'\n"
            + "         WHEN mid(given_name,2,1) = 'Q' THEN '17'\n"
            + "         WHEN mid(given_name,2,1) = 'R' THEN '18'\n"
            + "         WHEN mid(given_name,2,1) = 'S' THEN '19'\n"
            + "         WHEN mid(given_name,2,1) = 'T' THEN '20'\n"
            + "         WHEN mid(given_name,2,1) = 'U' THEN '21'\n"
            + "         WHEN mid(given_name,2,1) = 'V' THEN '22'\n"
            + "         WHEN mid(given_name,2,1) = 'W' THEN '23'\n"
            + "         WHEN mid(given_name,2,1) = 'X' THEN '24'\n"
            + "         WHEN mid(given_name,2,1) = 'Y' THEN '25'\n"
            + "         WHEN mid(given_name,2,1) = 'Z' THEN '26'\n"
            + "         ELSE 'X'END),\n"
            + "\n"
            + "    (CASE\n"
            + "         WHEN mid(given_name,3,1) = 'A' THEN '01'\n"
            + "         WHEN mid(given_name,3,1) = 'B' THEN '02'\n"
            + "         WHEN mid(given_name,3,1) = 'C' THEN '03'\n"
            + "         WHEN mid(given_name,3,1) = 'D' THEN '04'\n"
            + "         WHEN mid(given_name,3,1) = 'E' THEN '05'\n"
            + "         WHEN mid(given_name,3,1) = 'F' THEN '06'\n"
            + "         WHEN mid(given_name,3,1) = 'G' THEN '07'\n"
            + "         WHEN mid(given_name,3,1) = 'H' THEN '08'\n"
            + "         WHEN mid(given_name,3,1) = 'I' THEN '09'\n"
            + "         WHEN mid(given_name,3,1) = 'J' THEN '10'\n"
            + "         WHEN mid(given_name,3,1) = 'K' THEN '11'\n"
            + "         WHEN mid(given_name,3,1) = 'L' THEN '12'\n"
            + "         WHEN mid(given_name,3,1) = 'M' THEN '13'\n"
            + "         WHEN mid(given_name,3,1) = 'N' THEN '14'\n"
            + "         WHEN mid(given_name,3,1) = 'O' THEN '15'\n"
            + "         WHEN mid(given_name,3,1) = 'P' THEN '16'\n"
            + "         WHEN mid(given_name,3,1) = 'Q' THEN '17'\n"
            + "         WHEN mid(given_name,3,1) = 'R' THEN '18'\n"
            + "         WHEN mid(given_name,3,1) = 'S' THEN '19'\n"
            + "         WHEN mid(given_name,3,1) = 'T' THEN '20'\n"
            + "         WHEN mid(given_name,3,1) = 'U' THEN '21'\n"
            + "         WHEN mid(given_name,3,1) = 'V' THEN '22'\n"
            + "         WHEN mid(given_name,3,1) = 'W' THEN '23'\n"
            + "         WHEN mid(given_name,3,1) = 'X' THEN '24'\n"
            + "         WHEN mid(given_name,3,1) = 'Y' THEN '25'\n"
            + "         WHEN mid(given_name,3,1) = 'Z' THEN '26'\n"
            + "         ELSE 'X' END),\n"
            + "\n"
            + "    (CASE\n"
            + "         WHEN mid(family_name,1,1) = 'A' THEN '01'\n"
            + "         WHEN mid(family_name,1,1) = 'B' THEN '02'\n"
            + "         WHEN mid(family_name,1,1) = 'C' THEN '03'\n"
            + "         WHEN mid(family_name,1,1) = 'D' THEN '04'\n"
            + "         WHEN mid(family_name,1,1) = 'E' THEN '05'\n"
            + "         WHEN mid(family_name,1,1) = 'F' THEN '06'\n"
            + "         WHEN mid(family_name,1,1) = 'G' THEN '07'\n"
            + "         WHEN mid(family_name,1,1) = 'H' THEN '08'\n"
            + "         WHEN mid(family_name,1,1) = 'I' THEN '09'\n"
            + "         WHEN mid(family_name,1,1) = 'J' THEN '10'\n"
            + "         WHEN mid(family_name,1,1) = 'K' THEN '11'\n"
            + "         WHEN mid(family_name,1,1) = 'L' THEN '12'\n"
            + "         WHEN mid(family_name,1,1) = 'M' THEN '13'\n"
            + "         WHEN mid(family_name,1,1) = 'N' THEN '14'\n"
            + "         WHEN mid(family_name,1,1) = 'O' THEN '15'\n"
            + "         WHEN mid(family_name,1,1) = 'P' THEN '16'\n"
            + "         WHEN mid(family_name,1,1) = 'Q' THEN '17'\n"
            + "         WHEN mid(family_name,1,1) = 'R' THEN '18'\n"
            + "         WHEN mid(family_name,1,1) = 'S' THEN '19'\n"
            + "         WHEN mid(family_name,1,1) = 'T' THEN '20'\n"
            + "         WHEN mid(family_name,1,1) = 'U' THEN '21'\n"
            + "         WHEN mid(family_name,1,1) = 'V' THEN '22'\n"
            + "         WHEN mid(family_name,1,1) = 'W' THEN '23'\n"
            + "         WHEN mid(family_name,1,1) = 'X' THEN '24'\n"
            + "         WHEN mid(family_name,1,1) = 'Y' THEN '25'\n"
            + "         WHEN mid(family_name,1,1) = 'Z' THEN '26'\n"
            + "         ELSE 'X' END),\n"
            + "    (CASE\n"
            + "         WHEN mid(family_name,2,1) = 'A' THEN '01'\n"
            + "         WHEN mid(family_name,2,1) = 'B' THEN '02'\n"
            + "         WHEN mid(family_name,2,1) = 'C' THEN '03'\n"
            + "         WHEN mid(family_name,2,1) = 'D' THEN '04'\n"
            + "         WHEN mid(family_name,2,1) = 'E' THEN '05'\n"
            + "         WHEN mid(family_name,2,1) = 'F' THEN '06'\n"
            + "         WHEN mid(family_name,2,1) = 'G' THEN '07'\n"
            + "         WHEN mid(family_name,2,1) = 'H' THEN '08'\n"
            + "         WHEN mid(family_name,2,1) = 'I' THEN '09'\n"
            + "         WHEN mid(family_name,2,1) = 'J' THEN '10'\n"
            + "         WHEN mid(family_name,2,1) = 'K' THEN '11'\n"
            + "         WHEN mid(family_name,2,1) = 'L' THEN '12'\n"
            + "         WHEN mid(family_name,2,1) = 'M' THEN '13'\n"
            + "         WHEN mid(family_name,2,1) = 'N' THEN '14'\n"
            + "         WHEN mid(family_name,2,1) = 'O' THEN '15'\n"
            + "         WHEN mid(family_name,2,1) = 'P' THEN '16'\n"
            + "         WHEN mid(family_name,2,1) = 'Q' THEN '17'\n"
            + "         WHEN mid(family_name,2,1) = 'R' THEN '18'\n"
            + "         WHEN mid(family_name,2,1) = 'S' THEN '19'\n"
            + "         WHEN mid(family_name,2,1) = 'T' THEN '20'\n"
            + "         WHEN mid(family_name,2,1) = 'U' THEN '21'\n"
            + "         WHEN mid(family_name,2,1) = 'V' THEN '22'\n"
            + "         WHEN mid(family_name,2,1) = 'W' THEN '23'\n"
            + "         WHEN mid(family_name,2,1) = 'X' THEN '24'\n"
            + "         WHEN mid(family_name,2,1) = 'Y' THEN '25'\n"
            + "         WHEN mid(family_name,2,1) = 'Z' THEN '26'\n"
            + "         ELSE 'X'  END),\n"
            + "    (CASE\n"
            + "         WHEN mid(family_name,3,1) = 'A' THEN '01'\n"
            + "         WHEN mid(family_name,3,1) = 'B' THEN '02'\n"
            + "         WHEN mid(family_name,3,1) = 'C' THEN '03'\n"
            + "         WHEN mid(family_name,3,1) = 'D' THEN '04'\n"
            + "         WHEN mid(family_name,3,1) = 'E' THEN '05'\n"
            + "         WHEN mid(family_name,3,1) = 'F' THEN '06'\n"
            + "         WHEN mid(family_name,3,1) = 'G' THEN '07'\n"
            + "         WHEN mid(family_name,3,1) = 'H' THEN '08'\n"
            + "         WHEN mid(family_name,3,1) = 'I' THEN '09'\n"
            + "         WHEN mid(family_name,3,1) = 'J' THEN '10'\n"
            + "         WHEN mid(family_name,3,1) = 'K' THEN '11'\n"
            + "         WHEN mid(family_name,3,1) = 'L' THEN '12'\n"
            + "         WHEN mid(family_name,3,1) = 'M' THEN '13'\n"
            + "         WHEN mid(family_name,3,1) = 'N' THEN '14'\n"
            + "         WHEN mid(family_name,3,1) = 'O' THEN '15'\n"
            + "         WHEN mid(family_name,3,1) = 'P' THEN '16'\n"
            + "         WHEN mid(family_name,3,1) = 'Q' THEN '17'\n"
            + "         WHEN mid(family_name,3,1) = 'R' THEN '18'\n"
            + "         WHEN mid(family_name,3,1) = 'S' THEN '19'\n"
            + "         WHEN mid(family_name,3,1) = 'T' THEN '20'\n"
            + "         WHEN mid(family_name,3,1) = 'U' THEN '21'\n"
            + "         WHEN mid(family_name,3,1) = 'V' THEN '22'\n"
            + "         WHEN mid(family_name,3,1) = 'W' THEN '23'\n"
            + "         WHEN mid(family_name,3,1) = 'X' THEN '24'\n"
            + "         WHEN mid(family_name,3,1) = 'Y' THEN '25'\n"
            + "         WHEN mid(family_name,3,1) = 'Z' THEN '26'\n"
            + "         ELSE 'X' END),\n"
            + "\n"
            + "    (CASE\n"
            + "         WHEN left(middle_name,1) = 'A' THEN '01'\n"
            + "         WHEN left(middle_name,1) = 'B' THEN '02'\n"
            + "         WHEN left(middle_name,1) = 'C' THEN '03'\n"
            + "         WHEN left(middle_name,1) = 'D' THEN '04'\n"
            + "         WHEN left(middle_name,1) = 'E' THEN '05'\n"
            + "         WHEN left(middle_name,1) = 'F' THEN '06'\n"
            + "         WHEN left(middle_name,1) = 'G' THEN '07'\n"
            + "         WHEN left(middle_name,1) = 'H' THEN '08'\n"
            + "         WHEN left(middle_name,1) = 'I' THEN '09'\n"
            + "         WHEN left(middle_name,1) = 'J' THEN '10'\n"
            + "         WHEN left(middle_name,1) = 'K' THEN '11'\n"
            + "         WHEN left(middle_name,1) = 'L' THEN '12'\n"
            + "         WHEN left(middle_name,1) = 'M' THEN '13'\n"
            + "         WHEN left(middle_name,1) = 'N' THEN '14'\n"
            + "         WHEN left(middle_name,1) = 'O' THEN '15'\n"
            + "         WHEN left(middle_name,1) = 'P' THEN '16'\n"
            + "         WHEN left(middle_name,1) = 'Q' THEN '17'\n"
            + "         WHEN left(middle_name,1) = 'R' THEN '18'\n"
            + "         WHEN left(middle_name,1) = 'S' THEN '19'\n"
            + "         WHEN left(middle_name,1) = 'T' THEN '20'\n"
            + "         WHEN left(middle_name,1) = 'U' THEN '21'\n"
            + "         WHEN left(middle_name,1) = 'V' THEN '22'\n"
            + "         WHEN left(middle_name,1) = 'W' THEN '23'\n"
            + "         WHEN left(middle_name,1) = 'X' THEN '24'\n"
            + "         WHEN left(middle_name,1) = 'Y' THEN '25'\n"
            + "         WHEN left(middle_name,1) = 'Z' THEN '26'\n"
            + "\t\t WHEN left(middle_name,1) = ' ' THEN 'NULL'\n"
            + "         ELSE 'X' END)\n"
            + "    )  as UIC,uuid()\n"
            + "      from  (select given_name, middle_name, family_name,patient_id, gender,birthdate,country from patient join  person p on\n"
            + "          patient.patient_id = p.person_id join person_name on p.person_id = person_name.person_id join person_address pa on p.person_id = pa.person_id\n"
            + "      WHERE patient.patient_id NOT IN (SELECT patient_id from patient_identifier where identifier_type = (select patient_identifier_type_id from patient_identifier_type where uuid='877169c4-92c6-4cc9-bf45-1ab95faea242' )))as demo";
}
